<?php

namespace Database\Seeders;

use App\Models\Book;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class BookSeeder extends Seeder
{
    public function run(): void
    {
        $books = [
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9780771038525',
                'google_id' => 'Y41zAwAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '0771038526'],
                    ['type' => 'ISBN_13', 'identifier' => '9780771038525']
                ]),
                'title' => 'Sapiens',
                'subtitle' => 'A Brief History of Humankind',
                'authors' => 'Yuval Noah Harari',
                'description' => 'NATIONAL BESTSELLER - Destined to become a modern classic in the vein of Guns, Germs, and Steel, Sapiens is a lively, groundbreaking history of humankind told from a unique perspective.',
                'thumbnail' => 'https://books.google.com/books/content?id=Y41zAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'McClelland & Stewart',
                'published_date' => '2014-10-28',
                'page_count' => 512,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['History / Civilization', 'Social Science / Anthropology / Cultural & Social', 'Science / Life Sciences / Evolution']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9780804139304',
                'google_id' => 'ZH4oAwAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '080413930X'],
                    ['type' => 'ISBN_13', 'identifier' => '9780804139304']
                ]),
                'title' => 'Zero to One',
                'subtitle' => 'Notes on Startups, or How to Build the Future',
                'authors' => 'Peter Thiel, Blake Masters',
                'description' => '#1 NEW YORK TIMES BESTSELLER • "This book delivers completely new and refreshing ideas on how to create value in the world."—Mark Zuckerberg, CEO of Meta',
                'thumbnail' => 'https://books.google.com/books/content?id=ZH4oAwAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Crown',
                'published_date' => '2014-09-16',
                'page_count' => 224,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Business & Economics / Entrepreneurship', 'Business & Economics / Small Business']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9896530076',
                'google_id' => 'Fy_wwAEACAAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '9896530076'],
                    ['type' => 'ISBN_13', 'identifier' => '9789896530075']
                ]),
                'title' => 'Capitães da areia',
                'subtitle' => 'romance',
                'authors' => 'Jorge Amado, Pedro Costa',
                'description' => 'Romance clássico da literatura brasileira que retrata a vida de meninos de rua em Salvador.',
                'thumbnail' => 'https://books.google.com/books/content?id=Fy_wwAEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Leya',
                'published_date' => '2009-01-01',
                'page_count' => 286,
                'format' => 'paperback',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Literatura Brasileira', 'Clássicos']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9781781101063',
                'google_id' => 'ox9BiuVKM1cC',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '178110106X'],
                    ['type' => 'ISBN_13', 'identifier' => '9781781101063']
                ]),
                'title' => 'Harry Potter et la Coupe de Feu',
                'subtitle' => null,
                'authors' => 'J.K. Rowling',
                'description' => 'Harry Potter a quatorze ans et entre en quatrième année au collège de Poudlard. Une grande nouvelle attend Harry, Ron et Hermione à leur arrivée.',
                'thumbnail' => 'https://books.google.com/books/content?id=ox9BiuVKM1cC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Pottermore Publishing',
                'published_date' => '2015-12-08',
                'page_count' => 779,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Juvenile Fiction / Fantasy & Magic', 'Young Adult Fiction / Fantasy / Wizards & Witches']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9780807060100',
                'google_id' => 'RMqMDQAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '0807060100'],
                    ['type' => 'ISBN_13', 'identifier' => '9780807060100']
                ]),
                'title' => 'Man\'s Search for Meaning, Gift Edition',
                'subtitle' => 'Gift Edition',
                'authors' => 'Viktor E. Frankl',
                'description' => 'The bestselling Holocaust memoir about finding purpose and strength in times of despair—selected as a Library of Congress "10 Most Influential Books in America"',
                'thumbnail' => 'https://books.google.com/books/content?id=RMqMDQAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Beacon Press',
                'published_date' => '2014-10-28',
                'page_count' => 200,
                'format' => 'paperback',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Psychology / Movements / Existential', 'History / Modern / 20th Century / Holocaust']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9781781103074',
                'google_id' => 'PDcQCwAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '1781103070'],
                    ['type' => 'ISBN_13', 'identifier' => '9781781103074']
                ]),
                'title' => 'Harry Potter e a Pedra Filosofal',
                'subtitle' => null,
                'authors' => 'J.K. Rowling',
                'description' => 'Harry Potter não é um herói habitual. É apenas um miúdo magricela, míope e desajeitado com uma estranha cicatriz na testa.',
                'thumbnail' => 'https://books.google.com/books/content?id=PDcQCwAAQBAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Pottermore Publishing',
                'published_date' => '2015-12-08',
                'page_count' => 254,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Juvenile Fiction / Fantasy & Magic', 'Young Adult Fiction / Fantasy / Wizards & Witches']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9788580410082',
                'google_id' => 'Pw-5t-RLpVsC',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '8580410088'],
                    ['type' => 'ISBN_13', 'identifier' => '9788580410082']
                ]),
                'title' => 'Não conte a ninguém',
                'subtitle' => null,
                'authors' => 'Harlan Coben',
                'description' => 'Harlan Coben constrói uma história envolvente e eletrizante sobre perda e redenção, segredos inconfessáveis e um amor capaz de resistir a tudo.',
                'thumbnail' => 'https://books.google.com/books/content?id=Pw-5t-RLpVsC&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Editora Arqueiro',
                'published_date' => '2011-08-04',
                'page_count' => 256,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Fiction / Thrillers / Suspense', 'Fiction / Mystery & Detective']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9724608158',
                'google_id' => 'N1ddSQAACAAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '9724608158'],
                    ['type' => 'ISBN_13', 'identifier' => '9789724608150']
                ]),
                'title' => 'A profecia celestina: uma odisseia para o nosso tempo',
                'subtitle' => null,
                'authors' => 'James Redfield',
                'description' => 'Romance espiritual sobre as nove visões que revelam o destino da humanidade.',
                'thumbnail' => 'https://books.google.com/books/content?id=N1ddSQAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Ed. Notícias',
                'published_date' => '2004-01-01',
                'page_count' => 301,
                'format' => 'paperback',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Espiritualidade', 'Ficção']),
                'info_quality' => 'enhanced',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9781506721071',
                'google_id' => 'ZQMyEAAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '1506721079'],
                    ['type' => 'ISBN_13', 'identifier' => '9781506721071']
                ]),
                'title' => 'Stranger Things and Dungeons & Dragons (Graphic Novel)',
                'subtitle' => null,
                'authors' => 'Jody Houser, Jim Zub',
                'description' => 'Follow the crew from Hawkins, Indiana, as they discover the legendary monsters and epic adventures of the Dungeons & Dragons tabletop role-playing game together.',
                'thumbnail' => 'https://books.google.com/books/content?id=ZQMyEAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Dark Horse Comics',
                'published_date' => '2021-07-06',
                'page_count' => 96,
                'format' => 'paperback',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Comics & Graphic Novels / Media Tie-In', 'Comics & Graphic Novels / Fantasy']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9780385526951',
                'google_id' => '81nF3iyA640C',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '0385526954'],
                    ['type' => 'ISBN_13', 'identifier' => '9780385526951']
                ]),
                'title' => 'The Last Secret of Fatima',
                'subtitle' => 'The Revelation of One of the Most Controversial Events in Catholic History',
                'authors' => 'Cardinal Tarcisio Bertone',
                'description' => 'With an introduction by Pope Benedict XVI and including information previously suppressed, the Vatican\'s Secretary of State, Cardinal Bertone, definitively reveals and explains one of the most controversial events in twentieth-century Catholicism.',
                'thumbnail' => 'https://books.google.com/books/content?id=81nF3iyA640C&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'Crown Publishing Group',
                'published_date' => '2008-05-06',
                'page_count' => 192,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Religion / Christianity / Catholic', 'Religion / Christian Church / History']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '9781505108293',
                'google_id' => 'HuKNDAAAQBAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '1505108292'],
                    ['type' => 'ISBN_13', 'identifier' => '9781505108293']
                ]),
                'title' => 'Fatima\'s Message for Our Times',
                'subtitle' => null,
                'authors' => 'Rev. Msgr. Joseph A. Cirrincione',
                'description' => 'Summarizes the Fatima messages as a return to a life of prayer, to the traditional prayer life of the Catholic Church, especially to prayer before the Blessed Sacrament.',
                'thumbnail' => 'https://books.google.com/books/content?id=HuKNDAAAQBAJ&printsec=frontcover&img=1&zoom=1&edge=curl&source=gbs_api',
                'language' => 'pt-BR',
                'publisher' => 'TAN Books',
                'published_date' => '2009-01-01',
                'page_count' => 72,
                'format' => 'ebook',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Religion / Christian Theology / History', 'Religion / Christianity / Catholic']),
                'info_quality' => 'complete',
                'enriched_at' => now(),
            ],
            [
                'id' => 'B-' . strtoupper(Str::random(4)) . '-' . strtoupper(Str::random(4)),
                'isbn' => '8501404705',
                'google_id' => 'xyuyoAEACAAJ',
                'industry_identifiers' => json_encode([
                    ['type' => 'ISBN_10', 'identifier' => '8501404705'],
                    ['type' => 'ISBN_13', 'identifier' => '9788501404701']
                ]),
                'title' => 'Esquerda caviar',
                'subtitle' => 'a hipocrisia dos artistas e intelectuais progressistas no Brasil e no mundo',
                'authors' => 'Rodrigo Constantino',
                'description' => 'Análise crítica sobre contradições de intelectuais progressistas.',
                'thumbnail' => null,
                'language' => 'pt-BR',
                'publisher' => 'Editora Record',
                'published_date' => '2014-01-01',
                'page_count' => 432,
                'format' => 'paperback',
                'print_type' => 'BOOK',
                'categories' => json_encode(['Política', 'Ensaio']),
                'info_quality' => 'enhanced',
                'enriched_at' => now(),
            ],
        ];

        foreach ($books as $bookData) {
            Book::create($bookData);
        }
    }
}